---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app-two-namespace
  name: app-two-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-two-demo
  template:
    metadata:
      labels:
        app: app-two-demo
    spec:
      containers:
      - name: app-two-demo
        image: oryzaivt/demo-vso-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-two-demo-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-two-demo-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  namespace: app-two-namespace
  name: app-two-demo-service
spec:
  type: NodePort
  selector:
    app: app-two-demo
  ports:
    - protocol: TCP
      port: 8022
      targetPort: 8080
      nodePort: 30022
