---
apiVersion: v1
kind: Secret
metadata:
  namespace: app-four-namespace
  name: vault-secretid-app-four
stringData:
  # AppRole's `secret_id`, the key should be `id`
  id: 8cc763c5-4011-cf6d-11b5-e13edeb3a83e
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: app-four-namespace
  name: vault-secret
spec:
  # KV Engine Type
  type: kv-v2

  # KV mount path
  mount: kvv2

  # KV Secret's path
  path: app-four-secrets/app-config
  
  destination:
    # Secret's (Kubernetes Secret) name
    name: app-four-demo-secret
    create: true
  
  # RefreshAfter a period of time, in duration notation e.g. 30s, 1m, 24h
  refreshAfter: 30s

  # Trigger `rollout-restart` for specified target (Deployments, StatefulSets, etc.)
  rolloutRestartTargets:
  - kind: Deployment
    name: app-four-demo

  # VaultAuthRef to the VaultAuth resource
  vaultAuthRef: vault-secrets-operator-system/vault-auth-approle-app-four